Applicant Rating Classes & Database first draft
HdM-LLM/backend pull request #37
Opened 2023-12-04 10:17 UTC by MaxTyrchan

2023-12-04 14:18 UTC, ScottPalme requested changes

2023-12-04 14:18 UTC, ScottPalme commented on src/classes/category.py
> +class Category(BusinessObject, ABC):
This should not be abstract

2023-12-04 14:18 UTC, ScottPalme commented on src/classes/rating.py
> +class Rating(BusinessObject, ABC):
This should not be abstract

2023-12-04 14:18 UTC, ScottPalme commented on src/classes/skill.py
> +class Skill(BusinessObject, ABC):
This should not be abstract

2023-12-04 14:18 UTC, ScottPalme commented on src/db/mysql/tables_and_columns.sql
>      id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
Since the id is a uuid it should not be auto incremented it's a normal string in the end

2023-12-04 14:18 UTC, ScottPalme commented on src/db/mysql/tables_and_columns.sql
>      FirstName VARCHAR(100) NOT NULL,
Names of columns should be in lower case and separated with underscores

2023-12-05 09:27 UTC, NicoleSauer commented on src/classes/skill.py
> +        def get_appicant_id(self) -> uuid4:
Typo in 'applicant'

2023-12-05 09:27 UTC, NicoleSauer commented on src/classes/skill.py
> +        def set_appicant_id(self, appicant_id) -> None:
Typo in 'applicant'

2023-12-05 09:32 UTC, NicoleSauer reviewed
I only saw these typos because I use the [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) package. Highly recommended 😄

2023-12-05 09:32 UTC, NicoleSauer commented on src/classes/skill.py
> +            self._applicant_id = appicant_id
Typo in 'applicant'

2023-12-05 19:25 UTC, MaxTyrchan commented
> I only saw these typos because I use the [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) package. Highly recommended 😄

Funny thing is a even have spell checker activated but was too stupid to recognize the typo lol 🫠

2023-12-05 19:37 UTC, ScottPalme approved these changes

2023-12-05 19:37 UTC, merged